### ISSUE TITLE
CSVImportCommand base class doesn't handle utf-8 encoding

### ISSUE THREAD

**Issue by andreagrandi** [alphagov/land-availability-import#36]
@davidread I've noticed form the Traceback information that the problem is not in the `import_busstops.py` script but it's in the base importer class:

```
Traceback (most recent call last):
  File "import_busstops.py", line 68, in <module>
    import_busstops()
  File "/home/ubuntu/venvs/land-availability-import/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venvs/land-availability-import/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venvs/land-availability-import/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venvs/land-availability-import/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "import_busstops.py", line 65, in import_busstops
    command.run()
  File "/home/ubuntu/land-availability-import/importers.py", line 52, in run
    for count, row in enumerate(reader):
  File "/home/ubuntu/venvs/land-availability-import/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 2163: invalid start byte
```

I'm not sure about which encoding the original `Stops.csv` is using, but I've noticed that in `import_metrotubes.csv` we are using `encoding='ISO-8859-1'`, do you think they are using the same encoding?

**Comment by davidread** [comment]
Yup, latin1 works. I've got a PR - one sec.
